INCLUDES := -I../../../include # replace with the path to the header TransferMatrices.hpp
                               # in your own system.

all:
	g++ -std=c++20 -o bin/ising ising.cpp $(INCLUDES)
